### PR TITLE
[Anchor-149] Fix customer type not being properly resolved (when multiple types are configured)

### LINKED ISSUE #717: Anchor-platform searches for wrong customertype to validate if the receiver exists.
We configured a new receiving customer type, on top of our pre existing receiving_user .When
 using the id of this new customer type created to call transactions and I am receiving that the customer does not exist. Looking into the logs, I see this:

```Unable to find customer FindCustomer(id=*******, account=null, memo=null, type=receiving_user) due to Failure(code=customer.not.found, reason=, details=[], cause=Optional.empty, i18nData=Failure.I18nData(code=failure.i18.default, defaultMessage=, arguments=[]))

### PR DESCRIPTION
**Pull request by Ifropc**
<details>
  <summary>PR Checklist</summary>

### PR Structure

* [ ] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ ] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [ ] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [ ] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Adding iteration over customer types in validateSenderAndReceiver.

### Why

Should fix #717. Previously, this method was searching for the customer with a first type in the map. Now, it searches for all types. 

### Known limitations

Customer types must be mutually exclusive (i.e. same customer can NOT have multiple types at the same time)

### CODE REVIEW

File: anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java [hunk 1]
```diff
@@ -33,6 +33,14 @@ public GetCustomerResponse getCustomer(GetCustomerRequest request) throws NotFou
       if (maybeCustomer.isEmpty()) {
         throw new NotFoundException(
             String.format("customer for 'id' '%s' not found", request.getId()));
+      } else if (request.getType() != null) {
+        if (!request.getType().equals("sep31-sender")
+            && !request.getType().equals("sep31-receiver")) {
```
Comment (spolaore) [inline anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java:38]: Not sure if we should be hard-coding those types, this will probably break anchos using different types

Comment (Ifropc) [reply anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java:38]: This is a change in reference (example) implementation. In this example, Business server only accept this 2 types (and reject others)

Comment (spolaore) [reply anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java:38]: ah this is the reference server, my bad

**Comment by JakeUrban** [comment]
Hi Gleb, can we update the PR title to be more specific to whats being changed? That way someone can read the commit log and get a sense of what has changed.

File: core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java [hunk 2]
```diff
@@ -539,21 +539,53 @@ private void validateSenderAndReceiver()
...
 
-    // TODO: Populate customer type with the first receiver type; this is a temporary fix for cases
-    // where customerType is required
     Sep12Operation sep12Operation = Context.get().getAsset().getSep31().getSep12();
-    String receiverType = null;
+    Sep12GetCustomerResponse receiver;
+
+    // Fix for https://github.com/stellar/java-stellar-anchor-sdk/issues/717 (ANCHOR-149)
+    // TODO: check if there is a better way to do it, i.e. request a type first for a customer OR
+    // stop iteration after first hit.
```
Comment (JakeUrban) [inline core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:547]: Is there a reason we're not checking the customer status after each request and stopping if we get ACCEPTED?

File: core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java [hunk 3]
```diff
@@ -539,21 +539,53 @@ private void validateSenderAndReceiver()
...
+        infoF("Customer (receiver) info needed for request ({})", Context.get().getRequest());
+        throw new Sep31CustomerInfoNeededException(types.toString());
+      }
+      if (accepted.size() != 1) {
+        infoF(
+            "Ambiguous customer info for request ({}) having multiple accepted responses ({})",
+            Context.get().getRequest(),
+            accepted);
+        throw new Sep31AmbiguousCustomerInfoException(accepted.toString());
+      }
```
Comment (JakeUrban) [inline core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:580]: I'm struggling with that we should do in this scenario. The Anchor Platform v1 has the assumption that types are mutually exclusive, so if this happens, the AP should probably return 500 to the Sending Anchor, right?

I don't see any changes to the Anchor Platform in this PR, only the underlying Java SDK. Where is the logic for how the platform handles these AnchorExceptions?

Comment (Ifropc) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:580]: @JakeUrban 
org.stellar.anchor.reference.controller.GlobalControllerExceptionHandler

File: core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java (hunk 2 above)
Comment (Ifropc) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:547]: I don't think I'm following the question, can you elaborate please?

Comment (JakeUrban) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:547]: Right now the implementation makes all the requests, then checks all the statuses. Why don't we make a request & check the status before we make the next request?

File: core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java (hunk 3 above)
Comment (JakeUrban) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:580]: Ok, it looks like its throwing 500 for all exceptions that aren't specifically cased in the file. I don't see `AnchorException` listed, so I'm assuming 500 is returned?

Comment (Ifropc) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:580]: Yes. There are handlers for specific AnchorExceptions, but generic one returns 500

File: core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java (hunk 2 above)
Comment (Ifropc) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:547]: Do you suggest to request and check them one by one until ACCEPTED found?
We can do that. But if there is a misconfiguration  `Sep31AmbiguousCustomerInfoException` won't be thrown.

Comment (JakeUrban) [reply core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java:547]: Oh you're right. Ok, lets keep it as-is.

**Review by JakeUrban — APPROVED** [review]

**Review by lijamie98 — APPROVED** [review]

**Review by reecexlm — APPROVED** [review]
