### PR TITLE
core: Fix issue-331 memo value is being dropped when generating SEP-24 interactive URL JWT and more_info_url JWT

### LINKED ISSUE #331: SEP-24: memo value is being dropped when generating SEP-24 interactive URL JWT
### What version are you using?

MGI's currently deployed version (not sure).

### What did you do?

MGI is testing the SEP-24 flow using custodial mode in the demo wallet.

### What did you expect to see?

The memo encoded in the interactive URL JWT's `sub` value.

### What did you see instead?

The memo was omitted, and only the Stellar address was present.

Niranjan showed me the code. We're passing `token.account()` to `Jwt.of()`. Instead we need to be passing `token.sub()`.

### PR DESCRIPTION
**Pull request by lijamie98**
Closes #331

https://github.com/stellar/java-stellar-anchor-sdk/issues/331 

<details>
  <summary>PR Checklist</summary>

### PR Structure

* [x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [x] This PR avoids mixing refactoring changes with feature changes (split into two PRs
  otherwise).
* [x] This PR's title starts with name of package that is most changed in the PR, ex.
  `paymentservice.stellar`, or `all` or `doc` if the changes are broad or impact many
  packages.

### Thoroughness

* [x] This PR adds tests for the most critical parts of the new functionality or fixes.
</details>

### What

Fixed the memo value is being dropped when generating SEP-24 interactive URL JWT and more_info_url JWT

### Why

Bug

### Known limitations

N/A

### CODE REVIEW

File: core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java [hunk 1]
```diff
@@ -361,7 +361,7 @@ TransactionResponse fromTxn(Sep24Transaction txn, String lang)
   JwtToken buildRedirectJwtToken(String fullRequestUrl, JwtToken token, Sep24Transaction txn) {
     return JwtToken.of(
         fullRequestUrl,
-        token.getAccount(),
+        token.getSub(),
```
Comment (marcelosalloum) [inline core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java:364]: Both `getSub()` and `getAccount()` return the same result, right? What does "sub" mean? I think "account" might be clearer.

**Review by marcelosalloum — APPROVED** [review]

**Review by JakeUrban — APPROVED** [review]
This looks good. @marcelosalloum, `sub` can either be the Stellar account OR the Stellar account + the memo used to identify the user of a shared account.

File: core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java (hunk 1 above)
Comment (lijamie98) [reply core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java:364]: `sub` is the common `subject` field of a JWT. `account` is a fields of a SEP-10 JWT.
